apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-ss-config-volume
  labels:
    pvname: ss-config-volume
spec:
  capacity:
    storage: 50Mi
  persistentVolumeReclaimPolicy: Delete
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/kubernetes-pv-manual/ss-config-volume"




