apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ss-config-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  storageClassName: manual
  volumeName: "pv-ss-config-volume"


